# Decap CMS Configuration
# Replace with your actual backend settings from decapbridge.com

# Use DecapBridge auth (required)
backend:
  name: git-gateway
  repo: Waynexlink/dauyomglobalnigerianlimited
  branch: main
  identity_url: https://auth.decapbridge.com/sites/efadd86b-d438-4cfc-b7f2-d82c386d4ccf
  gateway_url: https://gateway.decapbridge.com

  # Quickly see who did what (optional)
  commit_messages:
    create: Create {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    update: Update {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    delete: Delete {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    uploadMedia: Upload “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    deleteMedia: Delete “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    openAuthoring: Message {{message}} - {{author-name}} <{{author-login}}> via DecapBridge

# Better Decap + Bridge logo (optional)
logo_url: https://decapbridge.com/decapcms-with-bridge.svg

# Add site links in DecapCMS (optional)
site_url: https://dauyom.com

media_folder: "src/content/cars"
public_folder: "/src/content/cars"

#

# Collections
collections:
  # Existing Blog Collection
  - name: "blog"
    label: "Blog Posts"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Image Alt Text", name: "imageAlt", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  # NEW: Cars Collection
  - name: "cars"
    label: "Car Inventory"
    folder: "src/content/cars"
    create: true
    slug: "{{year}}-{{make}}-{{model}}"
    preview_path: "cars/{{slug}}"
    summary: "{{year}} {{make}} {{model}}"
    thumbnail: "heroImage"

    fields:
      - { label: "Make", name: "make", widget: "string" }
      - { label: "Model", name: "model", widget: "string" }
      - { label: "Year", name: "year", widget: "number" }
      - { label: "Price (₦)", name: "price", widget: "number" }
      - { label: "Mileage", name: "mileage", widget: "number", required: false }
      - {
          label: "Transmission",
          name: "transmission",
          widget: "select",
          options: ["Automatic", "Manual"],
          default: "Automatic",
        }
      - {
          label: "Engine Size",
          name: "engineSize",
          widget: "string",
          required: false,
        }
      - {
          label: "Fuel Type",
          name: "fuelType",
          widget: "select",
          options: ["Petrol", "Diesel", "Hybrid", "Electric"],
          default: "Petrol",
        }
      - {
          label: "Condition",
          name: "condition",
          widget: "select",
          options: ["New", "Used"],
          default: "Used",
        }
      - {
          label: "Location",
          name: "location",
          widget: "string",
          required: false,
        }

      - { label: "Hero Image", name: "heroImage", widget: "image" }
      - {
          label: "Hero Image Alt",
          name: "heroImageAlt",
          widget: "string",
          required: false,
        }

      - label: "Gallery Images"
        name: "galleryImages"
        widget: "list"
        required: false
        field: { label: "Image", name: "image", widget: "image" }

      - {
          label: "Featured Car",
          name: "featured",
          widget: "boolean",
          default: false,
        }
      - { label: "Publish Date", name: "publishDate", widget: "datetime" }

      - {
          label: "Short Description",
          name: "description",
          widget: "string",
          hint: "1–2 sentence summary, optional",
          required: false,
        }
